exports.SET_WORK_DURATION = 'SET_WORK_DURATION';
exports.SET_SHORT_BREAK_DURATION = 'SET_SHORT_BREAK_DURATION';
exports.SET_LONG_BREAK_DURATION = 'SET_LONG_BREAK_DURATION';
exports.SET_SET_COUNT = 'SET_SET_COUNT';
